using System.Collections.Generic;

namespace SpellMigration.Core.Mapping
{
    /// <summary>
    /// Verified 1:1 column mapping between SpellEditor's `spell` table and
    /// AzerothCore's `spell_dbc` table. Confirmed by direct value-count and
    /// positional testing against real SpellEditor exports (234 columns,
    /// same order, renamed but not restructured).
    /// 
    /// Tuple order: (SpellEditorColumnName, SpellDbcColumnName)
    /// </summary>
    public static class ColumnMap
    {
        public static readonly IReadOnlyList<(string SpellEditorName, string SpellDbcName)> Pairs =
            new List<(string, string)>
            {
        ("ID", "ID"),
        ("Category", "Category"),
        ("Dispel", "DispelType"),
        ("Mechanic", "Mechanic"),
        ("Attributes", "Attributes"),
        ("AttributesEx", "AttributesEx"),
        ("AttributesEx2", "AttributesEx2"),
        ("AttributesEx3", "AttributesEx3"),
        ("AttributesEx4", "AttributesEx4"),
        ("AttributesEx5", "AttributesEx5"),
        ("AttributesEx6", "AttributesEx6"),
        ("AttributesEx7", "AttributesEx7"),
        ("Stances", "ShapeshiftMask"),
        ("Unknown1", "unk_320_2"),
        ("StancesNot", "ShapeshiftExclude"),
        ("Unknown2", "unk_320_3"),
        ("Targets", "Targets"),
        ("TargetCreatureType", "TargetCreatureType"),
        ("RequiresSpellFocus", "RequiresSpellFocus"),
        ("FacingCasterFlags", "FacingCasterFlags"),
        ("CasterAuraState", "CasterAuraState"),
        ("TargetAuraState", "TargetAuraState"),
        ("CasterAuraStateNot", "ExcludeCasterAuraState"),
        ("TargetAuraStateNot", "ExcludeTargetAuraState"),
        ("CasterAuraSpell", "CasterAuraSpell"),
        ("TargetAuraSpell", "TargetAuraSpell"),
        ("ExcludeCasterAuraSpell", "ExcludeCasterAuraSpell"),
        ("ExcludeTargetAuraSpell", "ExcludeTargetAuraSpell"),
        ("CastingTimeIndex", "CastingTimeIndex"),
        ("RecoveryTime", "RecoveryTime"),
        ("CategoryRecoveryTime", "CategoryRecoveryTime"),
        ("InterruptFlags", "InterruptFlags"),
        ("AuraInterruptFlags", "AuraInterruptFlags"),
        ("ChannelInterruptFlags", "ChannelInterruptFlags"),
        ("ProcFlags", "ProcTypeMask"),
        ("ProcChance", "ProcChance"),
        ("ProcCharges", "ProcCharges"),
        ("MaximumLevel", "MaxLevel"),
        ("BaseLevel", "BaseLevel"),
        ("SpellLevel", "SpellLevel"),
        ("DurationIndex", "DurationIndex"),
        ("PowerType", "PowerType"),
        ("ManaCost", "ManaCost"),
        ("ManaCostPerLevel", "ManaCostPerLevel"),
        ("ManaPerSecond", "ManaPerSecond"),
        ("ManaPerSecondPerLevel", "ManaPerSecondPerLevel"),
        ("RangeIndex", "RangeIndex"),
        ("Speed", "Speed"),
        ("ModalNextSpell", "ModalNextSpell"),
        ("StackAmount", "CumulativeAura"),
        ("Totem1", "Totem_1"),
        ("Totem2", "Totem_2"),
        ("Reagent1", "Reagent_1"),
        ("Reagent2", "Reagent_2"),
        ("Reagent3", "Reagent_3"),
        ("Reagent4", "Reagent_4"),
        ("Reagent5", "Reagent_5"),
        ("Reagent6", "Reagent_6"),
        ("Reagent7", "Reagent_7"),
        ("Reagent8", "Reagent_8"),
        ("ReagentCount1", "ReagentCount_1"),
        ("ReagentCount2", "ReagentCount_2"),
        ("ReagentCount3", "ReagentCount_3"),
        ("ReagentCount4", "ReagentCount_4"),
        ("ReagentCount5", "ReagentCount_5"),
        ("ReagentCount6", "ReagentCount_6"),
        ("ReagentCount7", "ReagentCount_7"),
        ("ReagentCount8", "ReagentCount_8"),
        ("EquippedItemClass", "EquippedItemClass"),
        ("EquippedItemSubClassMask", "EquippedItemSubclass"),
        ("EquippedItemInventoryTypeMask", "EquippedItemInvTypes"),
        ("Effect1", "Effect_1"),
        ("Effect2", "Effect_2"),
        ("Effect3", "Effect_3"),
        ("EffectDieSides1", "EffectDieSides_1"),
        ("EffectDieSides2", "EffectDieSides_2"),
        ("EffectDieSides3", "EffectDieSides_3"),
        ("EffectRealPointsPerLevel1", "EffectRealPointsPerLevel_1"),
        ("EffectRealPointsPerLevel2", "EffectRealPointsPerLevel_2"),
        ("EffectRealPointsPerLevel3", "EffectRealPointsPerLevel_3"),
        ("EffectBasePoints1", "EffectBasePoints_1"),
        ("EffectBasePoints2", "EffectBasePoints_2"),
        ("EffectBasePoints3", "EffectBasePoints_3"),
        ("EffectMechanic1", "EffectMechanic_1"),
        ("EffectMechanic2", "EffectMechanic_2"),
        ("EffectMechanic3", "EffectMechanic_3"),
        ("EffectImplicitTargetA1", "ImplicitTargetA_1"),
        ("EffectImplicitTargetA2", "ImplicitTargetA_2"),
        ("EffectImplicitTargetA3", "ImplicitTargetA_3"),
        ("EffectImplicitTargetB1", "ImplicitTargetB_1"),
        ("EffectImplicitTargetB2", "ImplicitTargetB_2"),
        ("EffectImplicitTargetB3", "ImplicitTargetB_3"),
        ("EffectRadiusIndex1", "EffectRadiusIndex_1"),
        ("EffectRadiusIndex2", "EffectRadiusIndex_2"),
        ("EffectRadiusIndex3", "EffectRadiusIndex_3"),
        ("EffectApplyAuraName1", "EffectAura_1"),
        ("EffectApplyAuraName2", "EffectAura_2"),
        ("EffectApplyAuraName3", "EffectAura_3"),
        ("EffectAmplitude1", "EffectAuraPeriod_1"),
        ("EffectAmplitude2", "EffectAuraPeriod_2"),
        ("EffectAmplitude3", "EffectAuraPeriod_3"),
        ("EffectMultipleValue1", "EffectMultipleValue_1"),
        ("EffectMultipleValue2", "EffectMultipleValue_2"),
        ("EffectMultipleValue3", "EffectMultipleValue_3"),
        ("EffectChainTarget1", "EffectChainTargets_1"),
        ("EffectChainTarget2", "EffectChainTargets_2"),
        ("EffectChainTarget3", "EffectChainTargets_3"),
        ("EffectItemType1", "EffectItemType_1"),
        ("EffectItemType2", "EffectItemType_2"),
        ("EffectItemType3", "EffectItemType_3"),
        ("EffectMiscValue1", "EffectMiscValue_1"),
        ("EffectMiscValue2", "EffectMiscValue_2"),
        ("EffectMiscValue3", "EffectMiscValue_3"),
        ("EffectMiscValueB1", "EffectMiscValueB_1"),
        ("EffectMiscValueB2", "EffectMiscValueB_2"),
        ("EffectMiscValueB3", "EffectMiscValueB_3"),
        ("EffectTriggerSpell1", "EffectTriggerSpell_1"),
        ("EffectTriggerSpell2", "EffectTriggerSpell_2"),
        ("EffectTriggerSpell3", "EffectTriggerSpell_3"),
        ("EffectPointsPerComboPoint1", "EffectPointsPerCombo_1"),
        ("EffectPointsPerComboPoint2", "EffectPointsPerCombo_2"),
        ("EffectPointsPerComboPoint3", "EffectPointsPerCombo_3"),
        ("EffectSpellClassMaskA1", "EffectSpellClassMaskA_1"),
        ("EffectSpellClassMaskA2", "EffectSpellClassMaskA_2"),
        ("EffectSpellClassMaskA3", "EffectSpellClassMaskA_3"),
        ("EffectSpellClassMaskB1", "EffectSpellClassMaskB_1"),
        ("EffectSpellClassMaskB2", "EffectSpellClassMaskB_2"),
        ("EffectSpellClassMaskB3", "EffectSpellClassMaskB_3"),
        ("EffectSpellClassMaskC1", "EffectSpellClassMaskC_1"),
        ("EffectSpellClassMaskC2", "EffectSpellClassMaskC_2"),
        ("EffectSpellClassMaskC3", "EffectSpellClassMaskC_3"),
        ("SpellVisual1", "SpellVisualID_1"),
        ("SpellVisual2", "SpellVisualID_2"),
        ("SpellIconID", "SpellIconID"),
        ("ActiveIconID", "ActiveIconID"),
        ("SpellPriority", "SpellPriority"),
        ("SpellName0", "Name_Lang_enUS"),
        ("SpellName1", "Name_Lang_enGB"),
        ("SpellName2", "Name_Lang_koKR"),
        ("SpellName3", "Name_Lang_frFR"),
        ("SpellName4", "Name_Lang_deDE"),
        ("SpellName5", "Name_Lang_enCN"),
        ("SpellName6", "Name_Lang_zhCN"),
        ("SpellName7", "Name_Lang_enTW"),
        ("SpellName8", "Name_Lang_zhTW"),
        ("SpellNameFlag0", "Name_Lang_esES"),
        ("SpellNameFlag1", "Name_Lang_esMX"),
        ("SpellNameFlag2", "Name_Lang_ruRU"),
        ("SpellNameFlag3", "Name_Lang_ptPT"),
        ("SpellNameFlag4", "Name_Lang_ptBR"),
        ("SpellNameFlag5", "Name_Lang_itIT"),
        ("SpellNameFlag6", "Name_Lang_Unk"),
        ("SpellNameFlag7", "Name_Lang_Mask"),
        ("SpellRank0", "NameSubtext_Lang_enUS"),
        ("SpellRank1", "NameSubtext_Lang_enGB"),
        ("SpellRank2", "NameSubtext_Lang_koKR"),
        ("SpellRank3", "NameSubtext_Lang_frFR"),
        ("SpellRank4", "NameSubtext_Lang_deDE"),
        ("SpellRank5", "NameSubtext_Lang_enCN"),
        ("SpellRank6", "NameSubtext_Lang_zhCN"),
        ("SpellRank7", "NameSubtext_Lang_enTW"),
        ("SpellRank8", "NameSubtext_Lang_zhTW"),
        ("SpellRankFlags0", "NameSubtext_Lang_esES"),
        ("SpellRankFlags1", "NameSubtext_Lang_esMX"),
        ("SpellRankFlags2", "NameSubtext_Lang_ruRU"),
        ("SpellRankFlags3", "NameSubtext_Lang_ptPT"),
        ("SpellRankFlags4", "NameSubtext_Lang_ptBR"),
        ("SpellRankFlags5", "NameSubtext_Lang_itIT"),
        ("SpellRankFlags6", "NameSubtext_Lang_Unk"),
        ("SpellRankFlags7", "NameSubtext_Lang_Mask"),
        ("SpellDescription0", "Description_Lang_enUS"),
        ("SpellDescription1", "Description_Lang_enGB"),
        ("SpellDescription2", "Description_Lang_koKR"),
        ("SpellDescription3", "Description_Lang_frFR"),
        ("SpellDescription4", "Description_Lang_deDE"),
        ("SpellDescription5", "Description_Lang_enCN"),
        ("SpellDescription6", "Description_Lang_zhCN"),
        ("SpellDescription7", "Description_Lang_enTW"),
        ("SpellDescription8", "Description_Lang_zhTW"),
        ("SpellDescriptionFlags0", "Description_Lang_esES"),
        ("SpellDescriptionFlags1", "Description_Lang_esMX"),
        ("SpellDescriptionFlags2", "Description_Lang_ruRU"),
        ("SpellDescriptionFlags3", "Description_Lang_ptPT"),
        ("SpellDescriptionFlags4", "Description_Lang_ptBR"),
        ("SpellDescriptionFlags5", "Description_Lang_itIT"),
        ("SpellDescriptionFlags6", "Description_Lang_Unk"),
        ("SpellDescriptionFlags7", "Description_Lang_Mask"),
        ("SpellToolTip0", "AuraDescription_Lang_enUS"),
        ("SpellToolTip1", "AuraDescription_Lang_enGB"),
        ("SpellToolTip2", "AuraDescription_Lang_koKR"),
        ("SpellToolTip3", "AuraDescription_Lang_frFR"),
        ("SpellToolTip4", "AuraDescription_Lang_deDE"),
        ("SpellToolTip5", "AuraDescription_Lang_enCN"),
        ("SpellToolTip6", "AuraDescription_Lang_zhCN"),
        ("SpellToolTip7", "AuraDescription_Lang_enTW"),
        ("SpellToolTip8", "AuraDescription_Lang_zhTW"),
        ("SpellToolTipFlags0", "AuraDescription_Lang_esES"),
        ("SpellToolTipFlags1", "AuraDescription_Lang_esMX"),
        ("SpellToolTipFlags2", "AuraDescription_Lang_ruRU"),
        ("SpellToolTipFlags3", "AuraDescription_Lang_ptPT"),
        ("SpellToolTipFlags4", "AuraDescription_Lang_ptBR"),
        ("SpellToolTipFlags5", "AuraDescription_Lang_itIT"),
        ("SpellToolTipFlags6", "AuraDescription_Lang_Unk"),
        ("SpellToolTipFlags7", "AuraDescription_Lang_Mask"),
        ("ManaCostPercentage", "ManaCostPct"),
        ("StartRecoveryCategory", "StartRecoveryCategory"),
        ("StartRecoveryTime", "StartRecoveryTime"),
        ("MaximumTargetLevel", "MaxTargetLevel"),
        ("SpellFamilyName", "SpellClassSet"),
        ("SpellFamilyFlags", "SpellClassMask_1"),
        ("SpellFamilyFlags1", "SpellClassMask_2"),
        ("SpellFamilyFlags2", "SpellClassMask_3"),
        ("MaximumAffectedTargets", "MaxTargets"),
        ("DamageClass", "DefenseType"),
        ("PreventionType", "PreventionType"),
        ("StanceBarOrder", "StanceBarOrder"),
        ("EffectDamageMultiplier1", "EffectChainAmplitude_1"),
        ("EffectDamageMultiplier2", "EffectChainAmplitude_2"),
        ("EffectDamageMultiplier3", "EffectChainAmplitude_3"),
        ("MinimumFactionId", "MinFactionID"),
        ("MinimumReputation", "MinReputation"),
        ("RequiredAuraVision", "RequiredAuraVision"),
        ("TotemCategory1", "RequiredTotemCategoryID_1"),
        ("TotemCategory2", "RequiredTotemCategoryID_2"),
        ("AreaGroupID", "RequiredAreasID"),
        ("SchoolMask", "SchoolMask"),
        ("RuneCostID", "RuneCostID"),
        ("SpellMissileID", "SpellMissileID"),
        ("PowerDisplayId", "PowerDisplayID"),
        ("EffectBonusMultiplier1", "EffectBonusMultiplier_1"),
        ("EffectBonusMultiplier2", "EffectBonusMultiplier_2"),
        ("EffectBonusMultiplier3", "EffectBonusMultiplier_3"),
        ("SpellDescriptionVariableID", "SpellDescriptionVariableID"),
        ("SpellDifficultyID", "SpellDifficultyID"),
            };

        /// <summary>Total column count. Any SpellEditor export with a different
        /// value count than this is malformed and should fail validation
        /// before mapping (this is exactly the bug that corrupted the first
        /// Prestillence DoT export).</summary>
        public const int ExpectedColumnCount = 234;

        private static Dictionary<string, string>? _seToDbc;
        public static IReadOnlyDictionary<string, string> SpellEditorToDbc =>
            _seToDbc ??= BuildLookup();

        private static Dictionary<string, string> BuildLookup()
        {
            var dict = new Dictionary<string, string>(Pairs.Count);
            foreach (var (se, dbc) in Pairs)
                dict[se] = dbc;
            return dict;
        }
    }
}